Performance (17 seconds less): Removing indentation by traversing all files
MichalLytek/typegraphql-prisma pull request #275
Opened 2022-04-14 03:50 UTC by NicolasLopes7

# Description
Basically, this PR removes the indentation on the last step, we were iterating over all files created in a `for .. of` What does this mean? The ForOf runs serially, so we're indenting every file one per time. with this change, every time we write a new file we're formatting with the `indentSize: 2`.

# How it was tested
I used the schema that I'm taking 60 seconds to generate the times every day in my current job. We have:
- 88 Models
- 90 Enums
- 110 Relations

# Results
First of all i used a profiler to try to figure out what's taking more time to generate the types. This part of the code was taking 17 seconds:
```ts
    for (const file of project.getSourceFiles()) {
      file.formatText({ indentSize: 2 });
    }
```
So, I removed it and now it takes just 35~40 secs to generate all the types

2022-04-14 03:50 UTC, NicolasLopes7 commented
cc @patrick-made @pyscriptbug

2022-04-14 03:52 UTC, NicolasLopes7 commented
@MichalLytek @jmfury Can you take a look?
Do we really need to indentate these files?

2022-04-14 06:55 UTC, MichalLytek commented
Yes, we need to format the code. In plenty of places I put raw statements, so the source code is badly formatted.
The design goal of `typegraphql-prisma` was to generate source code that can be changed by users, not some hidden abstract building blocks.
All we can do is to add a generator option to conditionally skip the indentation.

2022-04-14 11:08 UTC, NicolasLopes7 commented
> Yes, we need to format the code. In plenty of places I put raw statements, so the source code is badly formatted. The design goal of `typegraphql-prisma` was to generate source code that can be changed by users, not some hidden abstract building blocks. All we can do is add a generator option to conditionally skip the indentation.

Gotcha! I found an option to create the Project with a default indentationText. I pushed a commit with these changes, might this works!

2022-05-14 14:03 UTC, NicolasLopes7 commented
hey @MichalLytek, any reason to don't go ahead with it? Just pushed a new commit to indent the files by default on the writer, instead of sequentially indenting one by one.

2022-06-07 17:20 UTC, MichalLytek commented
@NicolasLopes7 I will take a look at that PR as ASAP as possible 😉

2022-07-27 11:39 UTC, MichalLytek commented
Unfortunately, it does not work well 😞 

![image](https://user-images.githubusercontent.com/10618781/181237767-3d38548d-ad4a-4a95-91d8-fed5575a5557.png)

@NicolasLopes7 Please find a setting that works faster and does not break existing snapshot tests (run `npm test`).

2022-07-27 11:39 UTC, MichalLytek requested changes
`formatText` is still required to return properly formatted source code

2023-01-18 10:23 UTC, MichalLytek commented
Closing as looks abandoned 🔒 
Feel free to fix the issues and open a new PR 😉

2023-01-18 10:23 UTC, closed without merging