Support generating ESM output
MichalLytek/typegraphql-prisma pull request #387
Opened 2023-05-17 20:45 UTC by nigelzor

re: #372

Setting `emitESM=true` in the generator's configuration will switch from using `require` to `import` calls in the generated code.

I haven't been successful in actually using the ESM output. Bi-directional relationships between models lead to circular dependencies in `*WhereInput` and `*ListRelationFilter` and cause the following error at start-up:

> ReferenceError: Cannot access 'FooWhereInput' before initialization
>     at file:///app/node_modules/@generated/type-graphql/resolvers/inputs/FooListRelationFilter.js:10:31

Even without setting `emitEsm=true`, changing imports to use filenames with extension makes Typescript with `moduleResolution=node16` stop complaining about missing types.

2023-05-18 18:09 UTC, MichalLytek requested changes
There is a lot of regression. `*.js` import should be emitted only for esm.

2023-05-18 19:01 UTC, nigelzor commented
This is how I'd originally written the change, but I didn't like needing to pass `options` into every import generator. If this is how you'd prefer to see it :ok_hand:.

2024-05-23 12:53 UTC, woss commented
i second this PR

2024-07-14 09:44 UTC, vko-online commented
So esm support not happening anytime soon right?

2024-10-21 16:35 UTC, PS1TD commented
+1 Need this)

2025-01-22 17:26 UTC, nigelzor commented
I'm no longer working on a product that uses typegraphql-prisma and won't be pushing this forward.

2025-01-22 17:26 UTC, closed without merging